### ISSUE TITLE
Restart build_no when release string otherwise changes

### ISSUE THREAD

**Issue by pquentin** [mbarkhau/pycalver#149]
The current `{build_no}` is global, and does not depend on the release at all. This is surprising. All projects on https://calver.org/ restart their "micro" numbering with each new release.

In other words, `pycalver test 'v201811.0007' '{pycalver}' --release final` gives `v202005.0008`, but I would expect `v202005.0000`. This is not really an issue, but I would be interested to understand your rationale here.

Thanks!

**Comment by mbarkhau** [comment]
I think you're running into something similar to what this issue is meant to deal with: https://gitlab.com/mbarkhau/pycalver/-/issues/7

**Comment by mbarkhau** [comment]
In any case `{build_no}` is a sequential build number. The semantics you're assuming would be for `{PATCH}`.

**Comment by pquentin** [comment]
Ah, indeed, `{PATCH}` is exactly what I was looking for, thanks. Should I have opened this in Gitlab?

**Comment by mbarkhau** [comment]
Yes, the main project is on gitlab, though I check here too, since so many people seem to think github is the only thing that exists in the world ;-)
