### ISSUE TITLE
pycalver init error

### ISSUE THREAD

**Issue by j-walker23** [mbarkhau/pycalver#2]
Hey, not sure if this is live yet but it looks awesome so I figured i'd give it a try.

I pip installed version 201812.11b0, and tried pip installing to your latest couple github releases.
Everytime i run `pycalver init` i get
`File not found: pycalver.toml`
`Created pycalver.toml`.
But the toml file is broken. Each character is set on a separate line.

**Comment by mbarkhau** [comment]
Hi, thanks for trying it. Indeed I didn't check the `init` command since the last refactoring. I'll have a look.

**Comment by mbarkhau** [comment]
I just published `pycalver-201812.16`, please give it a try.

**Comment by j-walker23** [comment]
Worked great, thanks!
